## First Notebook

In [1]:
import pandas as pd

In [2]:
df_system_book = pd.read_csv(r"C:\Users\Admin\Desktop\Module-5\DATA\03_Library Systembook.csv")
df_system_customers = pd.read_csv(r"C:\Users\Admin\Desktop\Module-5\DATA\03_Library SystemCustomers.csv")

### Clean df_system_book

In [3]:
df_system_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      21 non-null     float64
 1   Books                   20 non-null     object
 2   Book checkout           21 non-null     object
 3   Book Returned           21 non-null     object
 4   Days allowed to borrow  21 non-null     object
 5   Customer ID             20 non-null     float64
dtypes: float64(2), object(4)
memory usage: 5.5+ KB

In [4]:
df_system_book.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [5]:
df_system_book.tail(20)

     Id Books Book checkout Book Returned Days allowed to borrow  Customer ID
94  NaN   NaN           NaN           NaN                    NaN          NaN
95  NaN   NaN           NaN           NaN                    NaN          NaN
96  NaN   NaN           NaN           NaN                    NaN          NaN
97  NaN   NaN           NaN           NaN                    NaN          NaN
98  NaN   NaN           NaN           NaN                    NaN          NaN
99  NaN   NaN           NaN           NaN                    NaN          NaN
100 NaN   NaN           NaN           NaN                    NaN          NaN
101 NaN   NaN           NaN           NaN                    NaN          NaN
102 NaN   NaN           NaN           NaN                    NaN          NaN
103 NaN   NaN           NaN           NaN                    NaN          NaN
104 NaN   NaN           NaN           NaN                    NaN          NaN
105 NaN   NaN           NaN           NaN                    NaN          NaN
106 NaN   NaN           NaN           NaN                    NaN          NaN
107 NaN   NaN           NaN           NaN                    NaN          NaN
108 NaN   NaN           NaN           NaN                    NaN          NaN
109 NaN   NaN           NaN           NaN                    NaN          NaN
110 NaN   NaN           NaN           NaN                    NaN          NaN
111 NaN   NaN           NaN           NaN                    NaN          NaN
112 NaN   NaN           NaN           NaN                    NaN          NaN
113 NaN   NaN           NaN           NaN                    NaN          NaN

In [6]:
###Remove "" from Book checkout column and format as Date
df_system_book["Book checkout"] = df_system_book["Book checkout"].str.strip('""')
df_system_book["Book checkout"] = pd.to_datetime(df_system_book["Book checkout"],dayfirst = True, errors = "coerce")
df_system_book["Book checkout_Formated"] = df_system_book["Book checkout"].dt.strftime("%d/%m/%Y")

In [7]:
###Format from Book Returned column
df_system_book["Book Returned"] = pd.to_datetime(df_system_book["Book Returned"],dayfirst = True, errors = "coerce")
df_system_book["Book Returned_Formated"] = df_system_book["Book Returned"].dt.strftime("%d/%m/%Y")

In [8]:
##Remove weeks from days allowed to borrow and then x7 to return number of days
df_system_book["Days allowed to borrow"] = df_system_book["Days allowed to borrow"].str.strip('weeks')
df_system_book["Days allowed to borrow"] = pd.to_numeric(df_system_book["Days allowed to borrow"])*7
df_system_book["Days allowed to borrow"] = (df_system_book["Days allowed to borrow"].round(0).astype("Int64"))

In [9]:
## Sort out remaining column formats


df_system_book["Id"] = df_system_book["Id"].astype("Int64")
df_system_book["Customer ID"] = df_system_book["Customer ID"].astype("Int64")

df_system_book["Books"] = df_system_book["Books"].astype("string")

In [10]:
#Find Missing Values
df_system_book.isnull().sum()

Id                        93
Books                     94
Book checkout             94
Book Returned             93
Days allowed to borrow    93
Customer ID               94
Book checkout_Formated    94
Book Returned_Formated    93
dtype: int64

In [11]:
##Review the cleaning steps
df_system_book.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book checkout_Formated,Book Returned_Formated
0,1,Catcher in the Rye,2023-02-20,2023-02-25,14,1,20/02/2023,25/02/2023
1,2,Lord of the rings the two towers,2023-03-24,2023-03-21,14,2,24/03/2023,21/03/2023
2,3,Lord of the rings the return of the kind,2023-03-29,2023-03-25,14,3,29/03/2023,25/03/2023
3,4,The hobbit,2023-04-02,2023-03-25,14,4,02/04/2023,25/03/2023
4,5,Dune,2023-04-02,2023-03-25,14,5,02/04/2023,25/03/2023

In [12]:
print(df_system_book.shape)

(114, 8)

In [13]:
##Remove all nulls
df_system_book = df_system_book.dropna(how='all')

In [14]:
##Review how many rows still contain null
df_system_book.isnull().sum()

Id                        0
Books                     1
Book checkout             1
Book Returned             0
Days allowed to borrow    0
Customer ID               1
Book checkout_Formated    1
Book Returned_Formated    0
dtype: int64

In [15]:
#Review these null values
df_system_book[df_system_book.isnull().any(axis=1)]

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book checkout_Formated,Book Returned_Formated
16,17,The Bloody Chamber,NaT,2023-06-04,14,3,NaN,04/06/2023
20,21,<NA>,2023-06-01,2023-06-05,14,<NA>,01/06/2023,05/06/2023

In [16]:
##Create Error log -Could be developed further to add dates it was found and reason why its an error.
error_log = df_system_book[df_system_book.isnull().any(axis=1)].copy()
error_log.to_csv("error_log.csv", index=False)

In [17]:
##Review Ids for duplicates
df_system_book["Id"].duplicated().sum()

0

### Clean df_system_customers

In [18]:
df_system_customers.head(8)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling

In [19]:
print(df_system_customers.shape)

(9, 2)

In [20]:
##Remove all nulls
df_system_customers = df_system_customers.dropna(how='all')

In [21]:
##Review how many rows contain null
df_system_customers.isnull().sum()

Customer ID      0
Customer Name    0
dtype: int64

In [22]:
df_system_customers.head(8)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [23]:
##ID Validation Check
expected_ids = range(
    int(df_system_customers["Customer ID"].min()),
    int(df_system_customers["Customer ID"].max()) + 1
)

missing_ids = set(expected_ids) - set(df_system_customers["Customer ID"])

print(missing_ids)

{4}

In [24]:
##Log missing IDS for review
missing_customer_ids = pd.DataFrame({
    "Missing Customer ID": list(missing_ids)
})

missing_customer_ids["Error Reason"] = "Customer record missing"

missing_customer_ids.to_csv(
    "missing_customer_ids.csv",
    index=False
)

### Review Error Logs

In [25]:
df_system_book_error_log = pd.read_csv("error_log.csv")
df_system_book_error_log

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book checkout_Formated,Book Returned_Formated
0,17,The Bloody Chamber,NaN,2023-06-04,14,3.0,NaN,04/06/2023
1,21,NaN,2023-06-01,2023-06-05,14,NaN,01/06/2023,05/06/2023

In [26]:
df_system_customers_error_log = pd.read_csv("missing_customer_ids.csv")
df_system_customers_error_log

   Missing Customer ID             Error Reason
0                    4  Customer record missing

### Enrich Database System Book

In [27]:
df_system_book.head(10)
df_system_book.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      21 non-null     Int64
 1   Books                   20 non-null     string
 2   Book checkout           20 non-null     datetime64[ns]
 3   Book Returned           21 non-null     datetime64[ns]
 4   Days allowed to borrow  21 non-null     Int64
 5   Customer ID             20 non-null     Int64
 6   Book checkout_Formated  20 non-null     object
 7   Book Returned_Formated  21 non-null     object
dtypes: Int64(3), datetime64[ns](2), object(2), string(1)
memory usage: 1.5+ KB

In [31]:
print(df_system_book["Days Borrowed"].isna().sum())
print(df_system_book["Days allowed to borrow"].isna().sum())

1
0

In [55]:
df_system_book[df_system_book["Days Borrowed"].isna()]

Empty DataFrame
Columns: [Id, Books, Book checkout, Book Returned, Days allowed to borrow, Customer ID, Book checkout_Formated, Book Returned_Formated, Days Borrowed]
Index: []

In [ ]:
##Change the word NaT to nan
df_system_book["Book checkout"] = df_system_book["Book checkout"].replace(pd.NaT, np.nan)

In [57]:
##Remove those that do not have a checkout date, but these are in the error log to fix
df_system_book = df_system_book[
    df_system_book["Book checkout"].notna()
]

In [ ]:
##Calculate number of days borrowed

df_system_book["Days Borrowed"] = (
    df_system_book["Book Returned"] -
    df_system_book["Book checkout"]
).dt.days

In [68]:
##Change to function

def datediff(start_date, end_date):
    return(start_date-end_date).dt.days

In [58]:
df_system_book[["Days Borrowed", "Days allowed to borrow"]].dtypes

Days Borrowed             int64
Days allowed to borrow    Int64
dtype: object

In [59]:
##Estalish if the book was returned on time or late
import numpy as np

df_system_book["Status"] = np.where(
df_system_book["Book Returned"].isna(), "On Loan", np.where(
df_system_book["Days Borrowed"] > df_system_book["Days allowed to borrow"], "Returned Late", "Returned On Time"))

In [60]:
print(df_system_book["Status"].value_counts())

Status
Returned On Time    15
Returned Late        5
Name: count, dtype: int64

In [61]:
df_system_book.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Book checkout_Formated,Book Returned_Formated,Days Borrowed,Status
0,1,Catcher in the Rye,2023-02-20,2023-02-25,14,1,20/02/2023,25/02/2023,5,Returned On Time
1,2,Lord of the rings the two towers,2023-03-24,2023-03-21,14,2,24/03/2023,21/03/2023,-3,Returned On Time
2,3,Lord of the rings the return of the kind,2023-03-29,2023-03-25,14,3,29/03/2023,25/03/2023,-4,Returned On Time
3,4,The hobbit,2023-04-02,2023-03-25,14,4,02/04/2023,25/03/2023,-8,Returned On Time
4,5,Dune,2023-04-02,2023-03-25,14,5,02/04/2023,25/03/2023,-8,Returned On Time

### Output Clean data as CSV

In [74]:
df_system_book.to_csv(
    "clean_library_books.csv",
    index=False
)

error_log.to_csv(
    "library_books_error_log.csv",
    index=False
)


print("File saved")

File saved

### SQL Alchemy to write clean file to SSMS

In [69]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://@STUDENT01/QAETLStagingDB?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [70]:
with engine.connect() as conn:
    print("Connected successfully")

Connected successfully

In [ ]:
# Load cleaned data into SQL Server

df_system_book.to_sql(
    "LibraryBooks",
    con=engine,
    if_exists="replace",
    index=False
)

error_log.to_sql(
    "LibraryBooks_ErrorLog",
    con=engine,
    if_exists="replace",
    index=False
)

print("Clean System Book Data Loaded")

Clean System Book Data Loaded

In [73]:
# Load cleaned data into SQL Server

df_system_customers.to_sql(
    "LibraryBooks",
    con=engine,
    if_exists="replace",
    index=False
)

df_system_customers_error_log.to_sql(
    "LibraryBooks_ErrorLog",
    con=engine,
    if_exists="replace",
    index=False
)

print("Clean System Customer Data Loaded")

Clean System Customer Data Loaded